#
# ===========LICENSE_START====================================================
#  Copyright (C) 2020-2021 AT&T Intellectual Property. All rights reserved.
#  Modifications Copyright (C) 2021 Bell Canada. All rights reserved.
# ============================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=====================================================
#
version: '2'
services:
   db:
      image: mcr.microsoft.com/mssql/server
      container_name: db
      hostname: db 
      environment:
         ACCEPT_EULA: Y
         SA_PASSWORD: 123QWEasdzxc
      expose:
         - 1433
   liquibase:
      image: liquibase/liquibase
      container_name: liquibase
      depends_on:
       - db
      hostname: liquibase      
      environment:
         MYSQL_DATABASE: master
         MYSQL_ROOT_PASSWORD: 123QWEasdzxc
         MYSQL_USER: sa
         MYSQL_PASSWORD: 123QWEasdzxc
         CONTEXT: dev
      volumes:
         - ./config/db:/liquibase/changelog
         - ./liquibase_policy_init.sh:/liquibase/liquibase_policy_init.sh:ro
      command: [
                './liquibase_policy_init.sh'
               ]
      healthcheck:
              test: ["CMD", "curl", "-f", "http://db:1433"]
              interval: 60s
              timeout: 60s
              retries: 5
